### ISSUE TITLE
Use BBVA's public APIs?

### ISSUE THREAD

**Issue by bomberstudios** [bankscrap/bankscrap-bbva#1]
Just learnt about https://www.bbvaapimarket.com/web/api_market/products#bbva-products from a friend, and it looks like there's a way to access all the info without having to scrape their website.

Might be worth investigating : )

**Comment by javiercr** [comment]
@bomberstudios yes, indeed we have access to that API and we've had conversations with the API Market team to create a new adapter for that API and it is already in Bankscrap's roadmap.

However, there is a reason why we decided to still offer adapters for BBVA mobile app API ([bankscrap-bbva](https://github.com/bankscrap/bankscrap-bbva)) and BBVA Net Cash mobile app ([bankscrap-bbva-net-cash](https://github.com/bankscrap/bankscrap-net-cash)) API:
1. Right now the _public_ API is on alpha stage and to use it you need to require and invitation to it (and it may take some time), where the current Bankscrap adapters let use their APIs right away, just with your normal credentials.
2. The _public_ API doesn't offer the same level of detail for each transactions. For instance, last time we checked, the public API didn't provide the resulting balance after each transaction.
3. The _public_ API doesn't offer support for business accounts yet.

As I said to their devs, in my humble opinion the starting point for the _public_ API should be to provide the same features that their two other APIs offer – as **the two APIs behind [bankscrap-bbva](https://github.com/bankscrap/bankscrap-bbva) and [bankscrap-bbva-net-cash](https://github.com/bankscrap/bankscrap-net-cash) are also public APIs, they're just not documented**. 

I think the fact that projects like Bankscrap are unlocking these undocumented APIs is a good motivator for Banks to start working on well-documented and free APIs – we'll keep pushing until that times comes. As bank customers we think our financial data should belong to us, and we should be allowed to decide how to consume it.

Some banks we've talked to say they have problems to offer _public_ APIs because their legal teams say that could make phishing attacks way easier. They don't realize that someone who may want to do phishing only needs a few hours to find out what's the API behind the mobile apps they're already offering. And it doesn't matter if they do SSL certificate pinning, or code obfuscation.

There is one thing worth mentioning: on BBVA API Market's roadmap there is a future API for subscribing to notifications. I think that may be super useful, as it would avoid having to use polling for many use cases.

In any case, we definitely want to implement a new bankscrap-bbva-api-accounts (name may be different) adapter. I was planning to do this soon, but if you wanna go ahead an contribute to the project you will be more than welcome!

PS: note that BBVA API Market is a group of several APIs, the relevant one for Bankscrap is the [Accounts](https://www.bbvaapimarket.com/web/api_market/bbva/accounts) one.

PS2: kudos to the devs behind BBVA API Market, they're doing an awesome job within a very complex organization. I just hope their legal colleagues won't stop them.

**Comment by bomberstudios** [comment]
Thanks _a lot_ for the detailed answer. It is much appreciated : )
